import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function sendPredictionReport(data) {
  const {
    user,
    prediction,
    aiAdvice
  } = data;

  console.log("Email service started");
  console.log("Recipient:", user.email);
  console.log("Sender:", process.env.EMAIL_FROM);
  console.log(
    "Resend API key loaded:",
    Boolean(process.env.RESEND_API_KEY)
  );

  const actions = aiAdvice?.actions || [];

  const actionsHtml = actions
    .map(action => `<li>${action}</li>`)
    .join("");

  const { data: emailData, error } = await resend.emails.send({
    from: process.env.EMAIL_FROM,
    to: [user.email],
    subject: `🌾 Smart Agriculture - ${prediction.riskLevel} Crop Risk Prediction`,

    html: `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Crop Risk Prediction</title>
      </head>

      <body style="
        margin: 0;
        padding: 20px;
        background-color: #f4f7f5;
        font-family: Arial, sans-serif;
      ">

        <div style="
          max-width: 700px;
          margin: auto;
          background: white;
          padding: 30px;
          border-radius: 10px;
        ">

          <h1 style="text-align:center;">
            🌾 Smart Agriculture
          </h1>

          <h2 style="text-align:center;">
            Crop Risk Prediction Report
          </h2>

          <p>
            Hello <strong>${user.name || "User"}</strong>,
          </p>

          <p>
            Here is your complete crop prediction report.
          </p>

          <hr>

          <h3>👤 User Information</h3>

          <p>
            <strong>Name:</strong> ${user.name || "N/A"}
          </p>

          <p>
            <strong>Email:</strong> ${user.email || "N/A"}
          </p>

          <hr>

          <h3>📍 Location Details</h3>

          <p>
            <strong>State:</strong> ${prediction.state || "N/A"}
          </p>

          <p>
            <strong>District:</strong> ${prediction.district || "N/A"}
          </p>

          <p>
            <strong>Prediction Date:</strong> ${prediction.date || "N/A"}
          </p>

          <hr>

          <h3>🌾 Crop Details</h3>

          <p>
            <strong>Crop:</strong> ${prediction.crop || "N/A"}
          </p>

          <p>
            <strong>Soil Type:</strong> ${prediction.soilType || "N/A"}
          </p>

          <p>
            <strong>Irrigation:</strong> ${prediction.irrigationType || "N/A"}
          </p>

          <p>
            <strong>Previous Yield:</strong> ${prediction.previousYield ?? "N/A"}
          </p>

          <hr>

          <h3>🌦️ Weather Information</h3>

          <p>
            <strong>Temperature:</strong>
            ${prediction.temperature ?? "N/A"} °C
          </p>

          <p>
            <strong>Rainfall:</strong>
            ${prediction.rainfall ?? "N/A"} mm
          </p>

          <p>
            <strong>Humidity:</strong>
            ${prediction.humidity ?? "N/A"} %
          </p>

          <hr>

          <h3>🤖 ML Prediction</h3>

          <p>
            <strong>Heatwave Probability:</strong>
            ${prediction.heatwaveProbability ?? "N/A"}%
          </p>

          <p>
            <strong>Yield Loss Risk:</strong>
            ${prediction.yieldLossRisk ?? "N/A"}%
          </p>

          <p>
            <strong>Risk Level:</strong>
            ${prediction.riskLevel || "N/A"}
          </p>

          ${
            prediction.recommendation
              ? `
                <p>
                  <strong>Recommendation:</strong>
                  ${prediction.recommendation}
                </p>
              `
              : ""
          }

          <hr>

          <h3>🧠 AI Agriculture Advisor</h3>

          ${
            aiAdvice?.summary
              ? `
                <p>
                  <strong>Summary:</strong>
                  ${aiAdvice.summary}
                </p>
              `
              : ""
          }

          ${
            actions.length > 0
              ? `
                <p><strong>Recommendations:</strong></p>
                <ul>
                  ${actionsHtml}
                </ul>
              `
              : ""
          }

          ${
            aiAdvice?.priority
              ? `
                <p>
                  <strong>AI Priority:</strong>
                  ${aiAdvice.priority}
                </p>
              `
              : ""
          }

          <hr>

          <p style="text-align:center;">
            This report was generated by
            <strong>Smart Agriculture</strong>.
          </p>

        </div>

      </body>
      </html>
    `
  });

  if (error) {
    console.error("Resend email error:", error);
    throw new Error(error.message || "Email sending failed");
  }

  console.log(`Prediction report sent to ${user.email}`);

  return emailData;
}